### ISSUE TITLE
No response code while deleting CA certificate via Redfish

### ISSUE THREAD

**Issue by rahulmah** [openbmc/phosphor-certificate-manager#11]
No response code while deleting CA certificate via Redfish.

```
bash-4.2$ curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${BMC_IP}/redfish/v1/Managers/bmc/Truststore/Certificates/
{
  "@odata.context": "/redfish/v1/$metadata#CertificateCollection.CertificateCollection",
  "@odata.id": "/redfish/v1/Managers/bmc/Truststore/Certificates/",
  "@odata.type": "#CertificateCollection.CertificateCollection",
  "Description": "A Collection of TrustStore certificate instances",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Managers/bmc/Truststore/Certificates/14"
    },
    {
      "@odata.id": "/redfish/v1/Managers/bmc/Truststore/Certificates/15"
    }
  ],
  "Members@odata.count": 2,
  "Name": "TrustStore Certificates Collection"
}

bash-4.2$curl -c cjar -b cjar -k -H "X-Auth-Token: $bmc_token" -X DELETE https://$BMC_IP/redfish/v1/Managers/bmc/Truststore/Certificates/14   <----- No response code

bash-4.2$ curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${BMC_IP}/redfish/v1/Managers/bmc/Truststore/Certificates/
{
  "@odata.context": "/redfish/v1/$metadata#CertificateCollection.CertificateCollection",
  "@odata.id": "/redfish/v1/Managers/bmc/Truststore/Certificates/",
  "@odata.type": "#CertificateCollection.CertificateCollection",
  "Description": "A Collection of TrustStore certificate instances",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Managers/bmc/Truststore/Certificates/15"
    }
  ],
  "Members@odata.count": 1,
  "Name": "TrustStore Certificates Collection"
}

bash-4.2$
```

**Comment by rahulmah** [comment]
As per the Redfish output details.. Response code is coming as 204(No Content) in this case

```
bash-4.2$curl -c cjar -b cjar -k -H "X-Auth-Token: $bmc_token" -X DELETE https://${BMC_IP}/redfish/v1/Managers/bmc/Truststore/Certificates/<id> -vv
...
...
> DELETE /redfish/v1/Managers/bmc/Truststore/Certificates/<id> HTTP/1.1
> User-Agent: curl/7.29.0
> Host: <BMC_IP>
> Accept: */*
> X-Auth-Token: IOQqwpV2RjTwgL5nPChH
>
< HTTP/1.1 204 No Content              <----- Response code
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Frame-Options: DENY
< Pragma: no-cache
< Cache-Control: no-Store,no-Cache
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Content-Security-Policy: default-src 'none'; img-src 'self' data:; font-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self' wss:
< Server: iBMC
< Date: Mon, 10 Feb 2020 07:18:30 GMT
< Content-Length: 0
<
* Connection #0 to host <BMC_IP> left intact
```

**Comment by devenrao** [comment]
This is what is specified in the redfish specification, if the deleted certificate content cannot be retrieved, return "HTTP 204 No Content".
Agree that it would be good if certificate contents with HTTP 200 OK if returned is good, but as the developer choose to return "HTTP 204 No Content" which is allowed as per specification cannot treat it as a defect.

As for future enhancement please raise a issue (as a story) which specifies return the content of the delete resource as part of delete truststore certificate.

"
For update, replace, and delete operations, the response from the service, after successful modification,
should be one of the following responses:
• The HTTP 200 OK status code with a body that contains the JSON representation of the
targeted resource after the modification has been applied, or, for the delete operation, a
representation of the deleted resource.
• The HTTP 202 Accepted status code with a Location header set to the URI of a task
monitor when the processing of the modification requires additional time.
◦ After processing of the task is complete, the modified resource may be returned in
response to a request to the task monitor URI with the HTTP 200 OK status code.
• The HTTP 204 No Content status code with an empty payload in the event that service
cannot return a representation of the modified or deleted resource"
