### ISSUE TITLE
Missing "OU" OrganizationalUnit when generating CSR

### ISSUE THREAD

**Issue by josue0175** [openbmc/phosphor-certificate-manager#18]
When creating a CSR via Redfish, the Subject array has 5 fields including a required "OrganizationUnit".
However, the backedn is not applying the OrganizationalUnit to the CSR when generating it.

The fix is below:
```
diff --git a/redfish-core/lib/certificate_service.hpp b/redfish-core/lib/certificate_service.h
pp
index 81d9d05..d11a241 100644
--- a/redfish-core/lib/certificate_service.hpp
+++ b/redfish-core/lib/certificate_service.hpp
@@ -556,6 +556,10 @@ static void updateCertIssuerOrSubject(nlohmann::json& out,
         {
             out["State"] = val;
         }
+        else if (key == "emailAddress")
+        {
+            out["Email"] = val;
+        }
         // skip comma character
         if (i != value.end())
         {
```

**Comment by ojayanth** [comment]
Phosphor-cerificate manager back-end code related to CSR geneartion is not included OU info , that is causing this issue. I will push patch to fix this issue.

**Comment by ojayanth** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-certificate-manager/+/42910
