### ISSUE TITLE
Internal error while uploading client and CA certificate

### ISSUE THREAD

**Issue by rahulmah** [openbmc/phosphor-certificate-manager#19]
Internal error while uploading client and CA certificate.  

```
POSThttps://9.41.165.233/redfish/v1/AccountService/LDAP/Certificates/
[HTTP/1.1 500 Internal Server Error 340ms]

POSThttps://9.41.165.233/redfish/v1/Managers/bmc/Truststore/Certificates/
[HTTP/1.1 500 Internal Server Error 1907ms]
```

Please find attached the self-sign certificate which we tried uploading. (remove .txt from file extension to have .pem certificate)
[certificate.pem.txt](https://github.com/openbmc/phosphor-certificate-manager/files/6531643/certificate.pem.txt)

BMC firmware:
```
root@witherspoon:~# cat /etc/os-release
ID=openbmc-openpower
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.10.0-rc1"
VERSION_ID=2.10.0-rc1-dirty
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.10.0-rc1"
BUILD_ID="2.10.0-rc1"
OPENBMC_TARGET_MACHINE="witherspoon"
root@witherspoon:~#
```

**Comment by ojayanth** [comment]
Not seeing the issue with latest version Certificate manager @rahulmah please re-open if you still seeing issue with latest version.
