### ISSUE TITLE
Support uploading multiple certificates per service

### ISSUE THREAD

**Issue by devenrao** [openbmc/phosphor-certificate-manager#3]
At present it allows uploading only one certificate file per service.  It cater for replacing the certificate through bmcweb though.

Based on use case need to allow uploading multiple certificates

**Comment by devenrao** [comment]
duplicate issue

**Comment by devenrao** [comment]
it was raised in bmcweb as issue 84

**Comment by zkurzyns** [comment]
Proposition resolving this issue in 'authority' mode: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-certificate-manager/+/23348
